[package]
name = "Compose-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.25.0"
skia-safe = "0.66.2"
compose = { version = "0.1.0", path = "compose" }
compose_macro = { version = "0.1.0", path = "compose_macro" }
