[package]
name = "compose_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.38"
quote = "1.0.33"
rand = "0.8.5"
lazy_static = "1.4.0"
